<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZdBase\Module'                => __DIR__ . '/Module.php',
  'ZdBase\Module\AbstractModule' => __DIR__ . '/src/ZdBase/Module/AbstractModule.php',
);
