<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZdBase\Module'                         => __DIR__ . '/Module.php',
  'ZdBase\Form\Fieldset\AbstractFieldset' => __DIR__ . '/src/ZdBase/Form/Fieldset/AbstractFieldset.php',
  'ZdBase\Module\AbstractModule'          => __DIR__ . '/src/ZdBase/Module/AbstractModule.php',
);
